name: mind_safe
description: A Flutter project for SOS alerts.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  audioplayers: ^6.1.0
  google_generative_ai: ^0.4.6
  intl: ^0.19.0
  path_provider: ^2.0.11 # Check for the latest version on pub.dev
  http: ^1.2.2
  firebase_auth: ^5.3.1
  just_audio: ^0.9.41
  firebase_core: ^3.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/calming_music.mp3
